### ISSUE TITLE
App exits when rcon command fails

### ISSUE THREAD

**Issue by ragnarlonn** [ragnarlonn/mctimer#1]
Should probably wrap the commands in a try-except clause and reconnect when there's an exception.

```
Traceback (most recent call last):
  File "mctimer.py", line 103, in <module>
    main(servers)
  File "mctimer.py", line 92, in main
    response = rcons[i].command("/list")
  File "build/bdist.macosx-10.12-intel/egg/mcrcon.py", line 65, in command
  File "build/bdist.macosx-10.12-intel/egg/mcrcon.py", line 46, in send
  File "build/bdist.macosx-10.12-intel/egg/mcrcon.py", line 30, in read
socket.error: [Errno 54] Connection reset by peer
```

**Comment by ragnarlonn** [comment]
Closed via 0d93576
